export const GET_NOTES = 'GET_NOTES'
export const SAVE_NOTE = 'SAVE_NOTE'
export const SEARCH_NOTES = 'SEARCH_NOTES'
export const DELETE_NOTE = 'DELETE_NOTE'
export const EDIT_NOTE = 'EDIT_NOTE'
export const CREATE_NOTE = 'CREATE_NOTE'
export const NOTES_LOADING = 'NOTES_LOADING'
export const UPDATE_NOTE_TEXT = 'UPDATE_NOTE_TEXT'